version: '3'
services:
  lb:
    image: haproxy
    ports:
      - "8000:8000"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  dj_compose_instance_1:
    image: djcompose
    environment:
      - PORT=1111

  dj_compose_instance_2:
    image: djcompose
    environment:
      - PORT=2222

  dj_compose_instance_3:
    image: djcompose
    environment:
      - PORT=3333

  dj_compose_instance_4:
    image: djcompose
    environment:
      - PORT=4444

  dj_compose_instance_5:
    image: djcompose
    environment:
      - PORT=5555

  dj_compose_instance_6:
    image: djcompose
    environment:
      - PORT=6666

  dj_compose_instance_7:
    image: djcompose
    environment:
      - PORT=7777

  dj_compose_instance_8:
    image: djcompose
    environment:
      - PORT=8888
